
<div class="row-fluid">
	<p class="infosfooter">
		FORMULAIRE<br />
		Developpeur : 
			<?=$developpeur?> (<a href="http://<?=$developpeur_site?>" target="_blank" title="Visitez son site"><?=$developpeur_site_name?></a>)<br />
		&copy; 4 Septembre 2014 <br />- Pour <?=$compagnie_site_name?> (<a href="http://<?=$compagnie_site?>" target="_blank" title="Visitez le site de"><?=$compagnie_name?></a>) -
	</p>	
</div>